### ISSUE TITLE
saving stream to a file with multiple invocations of the handler

### ISSUE THREAD

**Issue by joe-rocko** [softprops/serverless-aws-rust-websockets#4]
Hi, great work on this!

Wondering what the best way to piece data together across invocations of the handler but restricted within a connection context. 

I considered saving to Dynamo but it seemed overkill. My current path is your [thread_local or global state](https://github.com/awslabs/aws-lambda-rust-runtime/issues/110#issuecomment-501113592) suggestion and use a map of vectors based on the unique RequestID and append the chunk of data to the appropriate buffer. One vector for each websocket session. I don't love that solution.

Any way to get the context of just the current websocket connection which ideally will deallocate the memory upon connection close? Or am I wishing for too much? Thanks!

**Comment by softprops** [comment]
The nature of of lambda is ephemeral by nature. They will get spun up and retired at whim. It's best not to think of them the same way you would with long lived servers.  That said you nothing stopping you from using a thread_local. You just can't rely on it for persistent state. 

For persistent state, dynamo or redis (elastic cache in aws) or another external store seems like a more reliable choice. 

Api gateway manages the actual socket connections for you, the lambda integration essentially gets a callback of life cycle events. you can get those events from the event.request_context. There's an example of a disconnect event [here](https://github.com/softprops/serverless-aws-rust-websockets/blob/a0fcb3664f34075c7e3473d8d639380d86cc24e3/connections/src/main.rs#L84)

**Comment by joe-rocko** [comment]
Thank you very much for the prompt reply. 

My expectation on how lambdas handled websockets in general was wrong. For my use case of consuming live streaming audio I thought I could handle it with one lambda invocation. But it makes sense that in the general case you don't want a long running lambda per connection that is mostly doing nothing.

**Comment by softprops** [comment]
An alternative I might suggest for this use case an aws fargate ecs service fronted by and alb.
